### ISSUE TITLE
Problem running

### ISSUE THREAD

**Issue by johnfcporto** [jd78/Chat#1]
I can't run your project.

After choosing an username i get an error

**Comment by jd78** [comment]
Which browser are you using? What kind of error? Client side or server side?

**Comment by johnfcporto** [comment]
I'm using Chrome..

First of all it says I'm missing a controller named ChatController..

![image](https://cloud.githubusercontent.com/assets/3793129/11122086/61033cde-8951-11e5-9425-0d3f03f5eb65.png)

If I remove this ChatController and run the app, i choose the username then i get this error

![image](https://cloud.githubusercontent.com/assets/3793129/11122143/bd9d10dc-8951-11e5-8754-7fb48c04c2d1.png)

server error in '/' application

**Comment by jd78** [comment]
Yup, was missed for some reason. I just reimplemented it. 
It should work fine now getting the latest version.

**Comment by johnfcporto** [comment]
thanks
