### ISSUE TITLE
Maintaining session

### ISSUE THREAD

**Issue by johnfcporto** [jd78/Chat#2]
Can you explain how do u handle page refreshing and session state?

I've been trying to implement that on my chat app.

Regards,

João

**Comment by jd78** [comment]
There is actually no page refresh, the messages are pushed through websockets, in that case I used SignalR. You should check my implementation for that in both client and server.
The session is kept through an in memory repository, the implementation is in Chat/Business. If you follow the code starting from the controllers is quite easy to understand.

Bear in mind that this is not production code, but just a demo/prototype. The application can't scale as is, the repository is in memory and not persisted anywhere, the websockets don't scale as well. As a final note, it's not lock free so the code should be improved.

It's fine just as possible implementation example and might even be used on a single server.
